server:
  port: 8081

thymeleaf:
cache: false

spring:
security:
oauth2:
client:
  registration:
    keycloak:
    client-id: nihongo
    client-secret: "SGqG0tmiAji9SkNPSaLoL8FFMiLOieMm"
    authorization-grant-type: authorization_code
    redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
    scope:
      - openid
      - profile
      - email
  provider:
    keycloak:
    issuer-uri: "http://localhost:8180/realms/nihongo"

  datasource:
    url: jdbc:mysql://localhost:3306/nihongo?useSSL=false&serverTimezone=UTC
    username: root
    password: thuthuyda1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # hoặc update/create/drop tùy môi trường
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
