server:
  port: 8081

spring:
  data:
    redis:
      url: redis://localhost:6379

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://db-host:3306/japanese?useSSL=false&serverTimezone=UTC
    username: root
    password: thuthuyda1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # hoặc update/create/drop tùy môi trường
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect